// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/b2345aee407127928f247165c91e18bd7dc1a14a/moment/moment.d.ts
declare var moment: moment.MomentStatic;
